var Promise, exec, execAsync, ref, run, spawn;

Promise = require('bluebird');

ref = require('child_process'), spawn = ref.spawn, exec = ref.exec;

execAsync = Promise.promisify(exec);

exports.hotspot = function(device) {
  switch (device) {
    case 'intel-edison':
    case 'edison':
      return run('modprobe -r bcm4334x', 'modprobe bcm4334x op_mode=2 firmware_path="firmware/intel-edison/fw_bcmdhd.bin" nvram_path="firmware/intel-edison/bcmdhd.cal"');
    default:
      return Promise.resolve();
  }
};

exports.normal = function(device) {
  switch (device) {
    case 'intel-edison':
    case 'edison':
      return run('modprobe -r bcm4334x', 'modprobe bcm4334x firmware_path="firmware/intel-edison/fw_bcmdhd.bin" nvram_path="firmware/intel-edison/bcmdhd.cal"');
    default:
      return Promise.resolve();
  }
};

run = function(disable, enable) {
  console.log('Loading kernel module: ' + enable);
  return execAsync(disable).delay(1000).then(function() {
    return execAsync(enable);
  }).delay(1000);
};

// ---
// generated by coffee-script 1.9.2
